### ISSUE TITLE
Pathways index currently showing only featured pathways

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/learningcurator#141]
Back ages ago when were navigating issues with CLDF we wanted to some pathways to remain published, but necessarily show up on the pathway index page, so a filter was put in place that only featured pathways would appear there. @ShannonLMitchell do we want to change that now? Put it back so that [the pathways index page](https://learningcurator.apps.silver.devops.gov.bc.ca/pathways) shows all published paths?

**Comment by ShannonLMitchell** [comment]
RIght! Okay, we solved that problem by not working with CLDF anymore and Learning Centre taking ownership of the Leadership pathways. Let's simplify that and put it back so the pathways index page shows all published ones. Thank you!
