### ISSUE TITLE
As a learner, in Safari keyboard tab order is completely broken

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/learningcurator#164]
Takes you to privacy statement and only the statement ... ?? how did this happen? Bad accessibility issue that isn't surfaced in Lighthouse for some reason. It's been like this for ages apparently.

**Comment by bcgov-noris** [comment]
Is this for all browsers? I couldn't reproduce this in Chrome in my nori.curator instance.

**Comment by allanhaggett** [comment]
My bad. Apparently it's only in Safari on Mac OS 👎 I'll look into myself and see what's up, but not nearly the priority I thought it was.
