### ISSUE TITLE
Edit database entries to remove html, consistency formatting

### ISSUE THREAD

**Issue by bcgov-noris** [bcgov/learningcurator#183]
Because we are now calling in descriptions/objectives etc. with h(text) and autoParagraph h(text) functions, html tags need to be removed from database entries. All entries should end with a period. And there may be other pieces that need to be checked for consistency.

**Comment by allanhaggett** [comment]
@ShannonLMitchell don't do this manually. I will auto-strip the HTML from the content when importing it into prod :)
