### ISSUE TITLE
HTML tags still showing in some views

### ISSUE THREAD

**Issue by bcgov-noris** [bcgov/learningcurator#281]
For example: https://learningcurator.apps.silver.devops.gov.bc.ca/find?search=diversity
search results - activities are showing tags.
Not sure the code is consistent about autoparagraph vs h() etc. around those description type fields.

**Comment by allanhaggett** [comment]
I meant to strip all the HTML on import and forgot to implement it :( I'll see what I can do to clean it up automagically, but we may have to just edit the activities individually

**Comment by bcgov-noris** [comment]
I don't mind working on stripping these if needed... but also wondered if I missed something in the search results code that they're showing there but no in the activity view or activity listing

**Comment by allanhaggett** [comment]
Probably means we're not using autopara in the act view / listing ... poke around see what you can see?

**Comment by bcgov-noris** [comment]
Fixed this, and also removed paragraph tags from activities in Live site. Note that some activities have super long descriptions...
