### ISSUE TITLE
Lengthen sign-in time.

### ISSUE THREAD

**Issue by ShannonLMitchell** [bcgov/learningcurator#32]
I'm being signed out within very brief periods of time. Just now I was working in the curator at 9:03 am, and then went to reply to some emails. When I returned to my curator work at 9:27 and followed a link, I was taken to the login screen again. I would expect to remain signed in unless I didn't touch the site for more than 2 hours, if I have to be signed out at all. Thanks!

**Comment by allanhaggett** [comment]
Switched to using file-based sessions so that we can persist them until a new reploy.
