### ISSUE TITLE
Create Report archive function

### ISSUE THREAD

**Issue by shannonator** [bcgov/learningcurator#38]
So we don't have a lot of responded-to and completed reports kicking around the system. A way to keep the reports-view clean to ones that are just still needing attention, whether or not we've responded to the person who sent the report.

**Comment by allanhaggett** [comment]
Lost track of commit but have started to remedy the situation (whole dashboard needs to be thought out more) but splitting this into two views: not responded to, and responded to. As you respond to comments, they move views. Still need, like, search and filter and better formatting and yeah...
