### ISSUE TITLE
CI/CD Pipeline - Automate deployment to TEST

### ISSUE THREAD

**Issue by kkapoor-fresh** [bcgov/learningcurator#56]

**Comment by allanhaggett** [comment]
Awesome!

**Comment by freshjwarren** [comment]
@kkapoor-fresh : Please confirm this is done

**Comment by allanhaggett** [comment]
@kkapoor-fresh only outstanding issue I can see here is the API key expires (Moodle had issue too). I currently have to replace the API with my personally generated key.
Thanks!
