### ISSUE TITLE
Pathway goal doesn't tell user how they interact with the page

### ISSUE THREAD

**Issue by allanhaggett** [bcgov/learningcurator#83]
@ShannonLMitchell could you elaborate on this one please?

**Comment by ShannonLMitchell** [comment]
As designed currently, the pathway goal gives the learner the "why" for following a pathway - the outcome they'll reach. But it doesn't give them a "how" which is being identified by users as a gap - they want to know how they should "do" a pathway. This would involve expanding pathway descriptions with additional guidance, which will be up to the curator but with recommendation provided by curation manager. Exactly what should be provided in the way of guidance on "how" to complete a pathway should be determined after we alpha-test the redesign, as it may become unneccessary.

**Comment by allanhaggett** [comment]
@ShannonLMitchell let's revisit this one soon
